services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks:
      - app-network
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=ats_db
      - DB_USERNAME=user
      - DB_PASSWORD=password
    entrypoint: ["/usr/local/bin/wait-for-it.sh", "db:5432", "--", "php-fpm"]

  web:
    image: nginx:alpine
    container_name: web
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - app-network

  db:
    image: postgres:latest
    container_name: laravel-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ats_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge