# Use the official PHP image as base
FROM php:8.3-fpm

# Set working directory
WORKDIR /var/www/html

# Install dependencies
RUN apt-get update && apt-get install -y \
    libpng-dev \
    libjpeg-dev \
    libfreetype6-dev \
	libpq-dev \
    zip \
    unzip \
    git \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install -j$(nproc) gd pdo pdo_mysql pdo_pgsql pgsql

# Install Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Copy application files
COPY . .

# Install PHP dependencies
RUN composer install --no-scripts --no-autoloader

# Run any additional commands (e.g., database migrations)
#RUN php artisan migrate

# Add wait-for-it script
COPY wait-for-it.sh /usr/local/bin/wait-for-it.sh

# Expose port 9000 and start PHP-FPM server
EXPOSE 9000
CMD ["php-fpm"]